#!/usr/bin/env python3
"""
AG2 Multi-Agent System — Production-Ready Example

A multi-agent system using AG2's GroupChat for automatic orchestration.
Agents collaborate to research topics and generate structured reports.

Usage:
    python app.py                         # Run with default query
    python app.py --interactive           # Interactive conversation mode
    python app.py --query "Your question" # Run a custom query
"""

import argparse
import os
from typing import Annotated

from dotenv import load_dotenv
from autogen import (
    AssistantAgent,
    UserProxyAgent,
    GroupChat,
    GroupChatManager,
    LLMConfig,
)

load_dotenv()

if not os.getenv("OPENAI_API_KEY"):
    raise EnvironmentError(
        "OPENAI_API_KEY not found. Copy .env.example to .env and add your key."
    )


# --- Tools ---


def search_knowledge_base(
    query: Annotated[str, "The search query to look up"],
    max_results: Annotated[int, "Maximum number of results to return"] = 3,
) -> str:
    """Search the internal knowledge base for relevant information."""
    knowledge = {
        "agent architectures": "Common patterns: ReAct, Plan-and-Execute, Multi-Agent Debate.",
        "deployment": "Key: containerization, API design, monitoring, graceful degradation.",
        "evaluation": "Metrics: task completion rate, latency, cost per query, user satisfaction.",
        "memory": "Types: short-term (conversation), long-term (vector DB), episodic memory.",
        "safety": "Implement: guardrails, content filtering, rate limiting, human-in-the-loop.",
        "scaling": "Strategies: horizontal scaling, caching, async processing, load balancing.",
        "monitoring": "Track: latency, error rates, token usage, conversation quality scores.",
    }
    results = []
    for topic, info in knowledge.items():
        if any(word in topic for word in query.lower().split()):
            results.append(f"- **{topic}**: {info}")
    return "\n".join(results[:max_results]) if results else "No results found for this query."


def generate_report(
    title: Annotated[str, "Report title"],
    content: Annotated[str, "Report content in markdown format"],
) -> str:
    """Generate a formatted report."""
    return f"# {title}\n\n{content}\n\n---\n*Generated by AG2 Multi-Agent System*"


# --- Agent Setup ---


def create_agents():
    """Create and configure the multi-agent system."""
    llm_config = LLMConfig({"model": "gpt-4o-mini"}, temperature=0.7)

    planner = AssistantAgent(
        name="Planner",
        system_message=(
            "You are a project planner. Break down tasks into clear steps "
            "and coordinate the team. Start by creating a plan."
        ),
        llm_config=llm_config,
    )
    researcher = AssistantAgent(
        name="Researcher",
        system_message=(
            "You are a research specialist. Use the search_knowledge_base tool "
            "to gather information. Provide factual, well-sourced findings."
        ),
        llm_config=llm_config,
    )
    writer = AssistantAgent(
        name="Writer",
        system_message=(
            "You are a technical writer. Create clear, well-structured content "
            "from research findings. Use the generate_report tool for final output."
        ),
        llm_config=llm_config,
    )
    reviewer = AssistantAgent(
        name="Reviewer",
        system_message=(
            "You review content for accuracy and completeness. "
            "Provide specific feedback. Say TERMINATE when quality is satisfactory."
        ),
        llm_config=llm_config,
    )
    user_proxy = UserProxyAgent(
        name="User",
        human_input_mode="NEVER",
        max_consecutive_auto_reply=10,
        code_execution_config=False,
    )

    # Register tools with the agents that need them
    researcher.register_for_llm(description="Search knowledge base")(search_knowledge_base)
    researcher.register_for_llm(description="Generate formatted report")(generate_report)
    writer.register_for_llm(description="Generate formatted report")(generate_report)
    user_proxy.register_for_execution()(search_knowledge_base)
    user_proxy.register_for_execution()(generate_report)

    # Create GroupChat with automatic speaker selection
    groupchat = GroupChat(
        agents=[user_proxy, planner, researcher, writer, reviewer],
        messages=[],
        max_round=12,
        speaker_selection_method="auto",
    )
    manager = GroupChatManager(groupchat=groupchat, llm_config=llm_config)

    return manager, user_proxy


# --- Main ---


def run_query(query: str):
    """Run a single query through the multi-agent system."""
    manager, user_proxy = create_agents()
    print(f"\n{'=' * 60}")
    print(f"Query: {query}")
    print(f"{'=' * 60}\n")

    result = user_proxy.initiate_chat(manager, message=query)

    if result and result.chat_history:
        # Find the last non-empty message from an agent (skip empty UserProxy replies)
        final_message = None
        for msg in reversed(result.chat_history):
            content = (msg.get("content") or "").strip()
            if content and content != "TERMINATE" and content != "TERMINATE.":
                final_message = content
                break
        if final_message:
            print(f"\n{'=' * 60}")
            print("Final Output:")
            print(f"{'=' * 60}")
            print(final_message)


def interactive_mode():
    """Run in interactive conversation mode."""
    print("AG2 Multi-Agent System (type 'exit' to quit)")
    print("-" * 50)

    while True:
        query = input("\nYou: ").strip()
        if query.lower() in ("exit", "quit", "q"):
            print("Goodbye!")
            break
        if not query:
            continue
        run_query(query)


def main():
    parser = argparse.ArgumentParser(description="AG2 Multi-Agent System")
    parser.add_argument("--interactive", action="store_true", help="Interactive mode")
    parser.add_argument("--query", type=str, help="Single query to run")
    args = parser.parse_args()

    if args.interactive:
        interactive_mode()
    elif args.query:
        run_query(args.query)
    else:
        # Default demo query
        run_query(
            "Create a brief guide on best practices for deploying AI agents "
            "to production. Cover architecture, monitoring, safety, and scaling."
        )


if __name__ == "__main__":
    main()
